[package]
name = "bridgetree"
version = "0.2.0"
authors = [
    "Kris Nuttycombe <kris@nutty.land>",
    "Sean Bowe <ewillbefull@gmail.com>",
]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A space-efficient Merkle tree designed for linear appends with witnessing of marked leaves, checkpointing & state restoration."
homepage = "https://github.com/zcash/incrementalmerkletree"
repository = "https://github.com/zcash/incrementalmerkletree"
categories = ["algorithms", "data-structures"]

[dependencies]
incrementalmerkletree = { version = "0.3", path = "../incrementalmerkletree" }
serde = { version = "1", features = ["derive"] }
proptest = { version = "1.0.0", optional = true }

[dev-dependencies]
incrementalmerkletree = { version = "0.3", path = "../incrementalmerkletree", features = ["test-dependencies"] }
proptest = "1.0.0"

[features]
test-dependencies = ["proptest"]
